name: Serah El-Rashidi
tagline: Aspiring Researcher | NLP AND AI Enthusiast | Passionate about DATA 
career-objective: |
  <i>The most damaging phrase in the language is "It’s always been done this way."</i> <br />
  - Grace Hopper <br /> <br />
  Hey there, call me Serah! I live in Lebanon and I plan on studying my phD abroad. I’m deeply involved in the Artificial Intelligence field and I believe in the usage of Ai for good, but we have a long road a head. I would like to make that road shorter and less desolate. My biggest wish is to make a positive impact on the world even if it was small. <br /> <br />
  Research Interests: NLP, Deep Learning, LLMS, Machine Learning, and AI ethics
color-theme: red # red or blue
avatar-filename: avatar.png # Change to your avatar's filename
url: academicportfolio.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: serah.elrashidi@gmail.com
  github: 
    visibility: true
    handle: arnobk
  linkedin: 
    visibility: true
    handle: https://www.linkedin.com/in/sarah-el-rashidi/ 
  twitter: 
    visibility: false 
    handle: arnobdotme

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Technical Skills
    visibility: true
  publications: 
    label: Publications
    visibility: false
  volunteerexperience: 
    label: Volunteer Experience
    visibility: true
  certifications: 
    label: Certifications
    visibility: true
  achievements: 
    label: Achievements
    visibility: false

navigation:
- title: About
  url: /
- title: My Begginers LeetCode Guide
  url: /leet/
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X
