name: Serah El-Rashidi
tagline: PhD Candidate | AI Research & Innovation | Creating Tomorrow's Technology Today
career-objective: |
  <i>"The most damaging phrase in the language is 'It's always been done this way.'"</i> <br />
  <em>— Grace Hopper</em> <br /> <br />
  Welcome to my academic journey! I'm Serah, a passionate researcher at the intersection of artificial intelligence and human-centered innovation. Based in Lebanon with global ambitions, I'm pursuing doctoral studies focused on advancing AI for social good. My mission is to bridge the gap between cutting-edge research and meaningful real-world applications. <br /> <br />
  <strong>Research Focus:</strong> Natural Language Processing • Deep Learning • Large Language Models • AI Ethics • Quantum Machine Learning
color-theme: purple # red, blue, or purple
url: academicportfolio.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: serah.elrashidi@gmail.com
  github: 
    visibility: true
    handle: its-serah
  linkedin: 
    visibility: true
    handle: sarah-el-rashidi
  twitter: 
    visibility: false 
    handle: arnobdotme

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: true
    sort_by: year
  workshops:
    output: true
    sort_by: year

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Technical Skills
    visibility: true
  publications: 
    label: Publications
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: true
  certifications: 
    label: Certifications
    visibility: true
  achievements:
    label: Awards & Recognitions
    visibility: true
  workshops:
    label: Workshops & Events
    visibility: true

navigation:
- title: About
  url: /
- title: Publications
  url: /publications
- title: Projects
  url: /projects
- title: Workshops & Events
  url: /workshops
- title: Awards & Achievements
  url: /achievements
- title: Personal
  url: /hobbies
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X
